[[setup]]
= Setup

To enable the {siren-url}[Siren] hypermedia type you simply need to add this library as a dependency to your project.
The library is accessible through {spring-hateoas-siren-artifact-source-url}[Maven Central] or one of its proxies.

[[maven]]
If you use {apache-maven-url}[Apache Maven], add the following to your build file:

.pom.xml
[source,xml,indent=0,subs="verbatim,quotes,attributes"]
----
<dependency>
    <groupId>de.ingogriebsch.hateoas</groupId>
    <artifactId>spring-hateoas-siren</artifactId>
    <version>{project-version}</version>
    <scope>compile</scope>
</dependency>
----

[[gradle]]
If you prefer to use {gradle-url}[Gradle], add the following to your build file:

.build.gradle.kts
[source,kotlin,indent=0,subs="verbatim,quotes,attributes"]
----
dependencies {
    implementation("de.ingogriebsch.hateoas:spring-hateoas-siren:{project-version}")
}
----

Having this library on the classpath is all you need in a Spring Boot based project to get the hypermedia type automatically enabled.

If you want to use the library in a project that is not based on Spring Boot, you need to use class `SirenMediaTypeConfiguration`.
This means, that you need to create an instance of this class and that you are responsible for that the methods that are necessary to initialize the library are executed.

This way incoming requests asking for the mentioned media type will get an appropriate response. The library is also able to deserialize a Json representation of the media type into corresponding {spring-hateoas-representation-model-url}[representation models].
